"""feature1_crowd_alert

Revision ID: b99649347bc1
Revises: d3e1e4795801
Create Date: 2026-06-04 03:27:04.972155+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

import app.models.types


revision: str = 'b99649347bc1'
down_revision: Union[str, Sequence[str], None] = 'd3e1e4795801'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crowd_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('visit_date', sa.Date(), nullable=False),
    sa.Column('hour_of_day', sa.Integer(), nullable=False),
    sa.Column('is_pournami', sa.Boolean(), nullable=False),
    sa.Column('is_festival', sa.Boolean(), nullable=False),
    sa.Column('free_wait_min', sa.Integer(), nullable=True),
    sa.Column('rs50_wait_min', sa.Integer(), nullable=True),
    sa.Column('rs200_wait_min', sa.Integer(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('hour_of_day BETWEEN 0 AND 23', name='ck_history_hour_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crowd_history_hour_of_day'), 'crowd_history', ['hour_of_day'], unique=False)
    op.create_index(op.f('ix_crowd_history_visit_date'), 'crowd_history', ['visit_date'], unique=False)
    op.create_table('crowd_status',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reported_at', sa.DateTime(), nullable=False),
    sa.Column('reported_by', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('free_wait_min', sa.Integer(), nullable=True),
    sa.Column('rs50_wait_min', sa.Integer(), nullable=True),
    sa.Column('rs200_wait_min', sa.Integer(), nullable=True),
    sa.Column('rs50_sold_out', sa.Boolean(), nullable=False),
    sa.Column('rs200_sold_out', sa.Boolean(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.CheckConstraint('free_wait_min IS NULL OR free_wait_min >= 0', name='ck_free_wait_nonneg'),
    sa.CheckConstraint('rs200_wait_min IS NULL OR rs200_wait_min >= 0', name='ck_rs200_wait_nonneg'),
    sa.CheckConstraint('rs50_wait_min IS NULL OR rs50_wait_min >= 0', name='ck_rs50_wait_nonneg'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crowd_status_reported_at'), 'crowd_status', ['reported_at'], unique=False)
    op.create_table('devotee_profiles',
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('has_elderly', sa.Boolean(), nullable=False),
    sa.Column('has_children', sa.Boolean(), nullable=False),
    sa.Column('planned_visit_date', sa.Date(), nullable=True),
    sa.Column('home_city', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=True),
    sa.Column('onboarding_state', sqlmodel.sql.sqltypes.AutoString(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('phone')
    )
    op.create_table('temple_config',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('temple_config')
    op.drop_table('devotee_profiles')
    op.drop_index(op.f('ix_crowd_status_reported_at'), table_name='crowd_status')
    op.drop_table('crowd_status')
    op.drop_index(op.f('ix_crowd_history_visit_date'), table_name='crowd_history')
    op.drop_index(op.f('ix_crowd_history_hour_of_day'), table_name='crowd_history')
    op.drop_table('crowd_history')
    # ### end Alembic commands ###
