"""processed_messages

Revision ID: c7e6d26aaaef
Revises: b99649347bc1
Create Date: 2026-06-30 02:44:37.310964+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

import app.models.types


revision: str = 'c7e6d26aaaef'
down_revision: Union[str, Sequence[str], None] = 'b99649347bc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_messages',
    sa.Column('message_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index(op.f('ix_processed_messages_first_seen_at'), 'processed_messages', ['first_seen_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processed_messages_first_seen_at'), table_name='processed_messages')
    op.drop_table('processed_messages')
    # ### end Alembic commands ###
