"""baseline_feature6_lodge_booking

Revision ID: d3e1e4795801
Revises: 
Create Date: 2026-05-29 13:40:19.400504+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

import app.models.types


revision: str = 'd3e1e4795801'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lodges',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('walk_minutes_to_temple', sa.Integer(), nullable=False),
    sa.Column('room_types', app.models.types.StringArray(), nullable=True),
    sa.Column('price_normal', sa.Integer(), nullable=False),
    sa.Column('price_pournami', sa.Integer(), nullable=False),
    sa.Column('price_karthigai', sa.Integer(), nullable=True),
    sa.Column('facilities', app.models.types.StringArray(), nullable=True),
    sa.Column('payment_accepted', app.models.types.StringArray(), nullable=True),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('total_bookings', sa.Integer(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('listing_fee_monthly', sa.Integer(), nullable=False),
    sa.Column('photo_urls', app.models.types.StringArray(), nullable=True),
    sa.Column('upi_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lodge_availability',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lodge_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('rooms_available', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('is_full', sa.Boolean(), nullable=False),
    sa.Column('update_source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.CheckConstraint('rooms_available >= 0', name='ck_rooms_nonneg'),
    sa.ForeignKeyConstraint(['lodge_id'], ['lodges.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lodge_id', 'date', name='uq_lodge_date')
    )
    op.create_index(op.f('ix_lodge_availability_date'), 'lodge_availability', ['date'], unique=False)
    op.create_index(op.f('ix_lodge_availability_lodge_id'), 'lodge_availability', ['lodge_id'], unique=False)
    op.create_table('lodge_bookings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('booking_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('devotee_phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('devotee_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lodge_id', sa.Uuid(), nullable=False),
    sa.Column('checkin_date', sa.Date(), nullable=False),
    sa.Column('checkin_time', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('room_rent', sa.Integer(), nullable=False),
    sa.Column('booking_fee', sa.Integer(), nullable=False),
    sa.Column('payment_method', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payment_verified', sa.Boolean(), nullable=False),
    sa.Column('lodge_confirmed', sa.Boolean(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('refund_amount', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('refund_amount >= 0', name='ck_booking_refund_nonneg'),
    sa.ForeignKeyConstraint(['lodge_id'], ['lodges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lodge_bookings_booking_ref'), 'lodge_bookings', ['booking_ref'], unique=True)
    op.create_index(op.f('ix_lodge_bookings_checkin_date'), 'lodge_bookings', ['checkin_date'], unique=False)
    op.create_index(op.f('ix_lodge_bookings_devotee_phone'), 'lodge_bookings', ['devotee_phone'], unique=False)
    op.create_index(op.f('ix_lodge_bookings_idempotency_key'), 'lodge_bookings', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_lodge_bookings_status'), 'lodge_bookings', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lodge_bookings_status'), table_name='lodge_bookings')
    op.drop_index(op.f('ix_lodge_bookings_idempotency_key'), table_name='lodge_bookings')
    op.drop_index(op.f('ix_lodge_bookings_devotee_phone'), table_name='lodge_bookings')
    op.drop_index(op.f('ix_lodge_bookings_checkin_date'), table_name='lodge_bookings')
    op.drop_index(op.f('ix_lodge_bookings_booking_ref'), table_name='lodge_bookings')
    op.drop_table('lodge_bookings')
    op.drop_index(op.f('ix_lodge_availability_lodge_id'), table_name='lodge_availability')
    op.drop_index(op.f('ix_lodge_availability_date'), table_name='lodge_availability')
    op.drop_table('lodge_availability')
    op.drop_table('lodges')
    # ### end Alembic commands ###
